// ============================================================
// Vision Glass & Interior — Email Service (Resend + Nodemailer fallback)
// ============================================================

import { Resend } from 'resend';
import nodemailer from 'nodemailer';
import dbConnect from '@/lib/db';
import Expense from '@/models/Expense';
import Employee from '@/models/Employee';
import { formatCurrency, formatDate, startOfDayUTC, endOfDayUTC, startOfMonthUTC, endOfMonthUTC } from '@/lib/utils';

const resend = process.env.RESEND_API_KEY ? new Resend(process.env.RESEND_API_KEY) : null;
const REPORT_EMAIL = process.env.REPORT_EMAIL_TO || 'admin@moneyflow.com';
const FROM_EMAIL = 'Vision Glass & Interior <onboarding@resend.dev>';

// Nodemailer fallback transporter
function getNodemailerTransport() {
  return nodemailer.createTransport({
    host: process.env.SMTP_HOST || 'smtp.gmail.com',
    port: parseInt(process.env.SMTP_PORT || '587', 10),
    secure: false,
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });
}

async function sendEmail(to: string, subject: string, html: string): Promise<boolean> {
  try {
    if (resend) {
      await resend.emails.send({
        from: FROM_EMAIL,
        to: [to],
        subject,
        html,
      });
      return true;
    }

    // Fallback to Nodemailer
    const transport = getNodemailerTransport();
    await transport.sendMail({
      from: FROM_EMAIL,
      to,
      subject,
      html,
    });
    return true;
  } catch (error) {
    console.error('Email send error:', error);
    return false;
  }
}

// ─── Email Templates ─────────────────────────────────────────

function baseTemplate(title: string, content: string): string {
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${title}</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8fafc; margin: 0; padding: 20px; }
        .container { max-width: 640px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
        .header { background: #6366f1; padding: 24px 32px; }
        .header h1 { color: #ffffff; margin: 0; font-size: 20px; font-weight: 600; }
        .header p { color: rgba(255,255,255,0.8); margin: 4px 0 0; font-size: 14px; }
        .body { padding: 32px; }
        table { width: 100%; border-collapse: collapse; margin: 16px 0; }
        th { background: #f1f5f9; text-align: left; padding: 10px 12px; font-size: 12px; font-weight: 600; text-transform: uppercase; color: #64748b; border-bottom: 2px solid #e2e8f0; }
        td { padding: 10px 12px; font-size: 14px; color: #334155; border-bottom: 1px solid #f1f5f9; }
        .total-row td { font-weight: 700; background: #f8fafc; border-top: 2px solid #e2e8f0; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 999px; font-size: 11px; font-weight: 600; }
        .badge-cash { background: #ecfdf5; color: #059669; }
        .badge-upi { background: #eff6ff; color: #2563eb; }
        .footer { padding: 20px 32px; background: #f8fafc; text-align: center; font-size: 12px; color: #94a3b8; }
        .stat-box { display: inline-block; padding: 16px 24px; margin: 8px; background: #f8fafc; border-radius: 8px; text-align: center; }
        .stat-value { font-size: 24px; font-weight: 700; color: #6366f1; }
        .stat-label { font-size: 12px; color: #64748b; margin-top: 4px; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <h1>Vision Glass & Interior</h1>
          <p>${title}</p>
        </div>
        <div class="body">
          ${content}
        </div>
        <div class="footer">
          Generated by Vision Glass & Interior on ${formatDate(new Date(), 'dd MMM yyyy, hh:mm a')}
        </div>
      </div>
    </body>
    </html>
  `;
}

// ─── Daily Report ────────────────────────────────────────────

export async function sendDailyReport(date: Date): Promise<boolean> {
  await dbConnect();

  const dayStart = startOfDayUTC(date);
  const dayEnd = endOfDayUTC(date);

  const expenses = await Expense.find({
    date: { $gte: dayStart, $lte: dayEnd },
  })
    .populate('employee', 'name employeeId')
    .sort({ date: -1 })
    .lean();

  if (expenses.length === 0) {
    return true; // No expenses, skip sending
  }

  const total = expenses.reduce((sum, e) => sum + e.amount, 0);
  const cashTotal = expenses
    .filter((e) => e.paymentMode === 'cash')
    .reduce((sum, e) => sum + e.amount, 0);
  const upiTotal = expenses
    .filter((e) => e.paymentMode === 'upi')
    .reduce((sum, e) => sum + e.amount, 0);

  const dateStr = formatDate(date, 'dd MMM yyyy');

  const rows = expenses
    .map((e) => {
      const emp = e.employee as unknown as { name: string; employeeId: string };
      return `
      <tr>
        <td>${emp?.name || 'Unknown'}</td>
        <td>${formatCurrency(e.amount)}</td>
        <td><span class="badge badge-${e.paymentMode}">${e.paymentMode.toUpperCase()}</span></td>
        <td>${e.description}</td>
      </tr>
    `;
    })
    .join('');

  const content = `
    <h2 style="margin-top:0;color:#1e293b;">Daily Expense Report — ${dateStr}</h2>
    <div style="text-align:center;margin:24px 0;">
      <div class="stat-box">
        <div class="stat-value">${formatCurrency(cashTotal)}</div>
        <div class="stat-label">Cash</div>
      </div>
      <div class="stat-box">
        <div class="stat-value">${formatCurrency(upiTotal)}</div>
        <div class="stat-label">UPI</div>
      </div>
      <div class="stat-box">
        <div class="stat-value">${formatCurrency(total)}</div>
        <div class="stat-label">Total</div>
      </div>
    </div>
    <table>
      <thead>
        <tr>
          <th>Employee</th>
          <th>Amount</th>
          <th>Payment</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
        <tr class="total-row">
          <td>Total (${expenses.length} expenses)</td>
          <td>${formatCurrency(total)}</td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  `;

  return sendEmail(
    REPORT_EMAIL,
    `Daily Expense Report — ${dateStr}`,
    baseTemplate(`Daily Report — ${dateStr}`, content)
  );
}

// ─── Monthly Report ──────────────────────────────────────────

export async function sendMonthlyReport(month: Date): Promise<boolean> {
  await dbConnect();

  const monthStart = startOfMonthUTC(month);
  const monthEnd = endOfMonthUTC(month);

  // Previous month for comparison
  const prevMonthDate = new Date(month);
  prevMonthDate.setUTCMonth(prevMonthDate.getUTCMonth() - 1);
  const prevMonthStart = startOfMonthUTC(prevMonthDate);
  const prevMonthEnd = endOfMonthUTC(prevMonthDate);

  const [currentExpenses, prevExpenses] = await Promise.all([
    Expense.aggregate([
      { $match: { date: { $gte: monthStart, $lte: monthEnd } } },
      {
        $group: {
          _id: '$employee',
          total: { $sum: '$amount' },
          count: { $sum: 1 },
          cashTotal: {
            $sum: { $cond: [{ $eq: ['$paymentMode', 'cash'] }, '$amount', 0] },
          },
          upiTotal: {
            $sum: { $cond: [{ $eq: ['$paymentMode', 'upi'] }, '$amount', 0] },
          },
        },
      },
    ]),
    Expense.aggregate([
      { $match: { date: { $gte: prevMonthStart, $lte: prevMonthEnd } } },
      {
        $group: {
          _id: '$employee',
          total: { $sum: '$amount' },
        },
      },
    ]),
  ]);

  if (currentExpenses.length === 0) {
    return true;
  }

  // Get employee details
  const employeeIds = currentExpenses.map((e) => e._id);
  const employees = await Employee.find({ _id: { $in: employeeIds } })
    .select('name employeeId')
    .lean();

  const employeeMap = new Map(employees.map((e) => [e._id.toString(), e]));
  const prevMap = new Map(
    prevExpenses.map((e) => [e._id.toString(), e.total])
  );

  const grandTotal = currentExpenses.reduce((sum, e) => sum + e.total, 0);
  const prevGrandTotal = prevExpenses.reduce((sum, e) => sum + e.total, 0);
  const monthStr = formatDate(month, 'MMMM yyyy');

  const rows = currentExpenses
    .map((e) => {
      const emp = employeeMap.get(e._id.toString());
      const prevTotal = prevMap.get(e._id.toString()) || 0;
      const delta = e.total - prevTotal;
      const deltaClass = delta > 0 ? 'color:#ef4444' : delta < 0 ? 'color:#10b981' : '';

      return `
      <tr>
        <td>${emp?.name || 'Unknown'} (${emp?.employeeId || ''})</td>
        <td>${formatCurrency(e.total)}</td>
        <td>${formatCurrency(e.cashTotal)}</td>
        <td>${formatCurrency(e.upiTotal)}</td>
        <td>${e.count}</td>
        <td style="${deltaClass}">${delta > 0 ? '+' : ''}${formatCurrency(Math.abs(delta))}</td>
      </tr>
    `;
    })
    .join('');

  const content = `
    <h2 style="margin-top:0;color:#1e293b;">Monthly Summary — ${monthStr}</h2>
    <div style="text-align:center;margin:24px 0;">
      <div class="stat-box">
        <div class="stat-value">${formatCurrency(grandTotal)}</div>
        <div class="stat-label">This Month</div>
      </div>
      <div class="stat-box">
        <div class="stat-value">${formatCurrency(prevGrandTotal)}</div>
        <div class="stat-label">Last Month</div>
      </div>
    </div>
    <table>
      <thead>
        <tr>
          <th>Employee</th>
          <th>Total</th>
          <th>Cash</th>
          <th>UPI</th>
          <th>Count</th>
          <th>vs Last Month</th>
        </tr>
      </thead>
      <tbody>
        ${rows}
        <tr class="total-row">
          <td>Grand Total</td>
          <td>${formatCurrency(grandTotal)}</td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
    </table>
  `;

  return sendEmail(
    REPORT_EMAIL,
    `Monthly Summary — ${monthStr}`,
    baseTemplate(`Monthly Summary — ${monthStr}`, content)
  );
}
